### ISSUE TITLE
Last run...

### ISSUE THREAD

**Issue by smartcuc** [coviddata/coviddata#13] opened 2020-04-02 11:47 UTC
FYI, in the last update USA is shown wrong figures..

**Comment by bfosten** [comment] 2020-04-02 16:52
Could you please provide the following clarifying information?

1. Which value(s) within this repository are you referring to? Please provide the URL(s) and the exact value(s).
1. Which value(s) outside of this repository are you using as a reference? Please provide the URL(s) and the exact value(s).

**Comment by bfosten** [comment] 2020-04-02 17:32
I'm assuming that this is a duplicate of #15. Please see #15 for the resolution.

**Closed as completed by bfosten** 2020-04-02 17:32 UTC
